PROJECT=iron_boot
CPU ?= cortex-m3
BOARD ?= stm32vldiscovery

qemu:
	arm-none-eabi-gcc -mthumb -mcpu=$(CPU) -g -c iron_boot.S -o iron_boot.o
	arm-none-eabi-ld -Tmap.ld iron_boot.o -o iron_boot.elf
	arm-none-eabi-objdump -D -S iron_boot.elf > iron_boot.elf.lst
	arm-none-eabi-readelf -a iron_boot.elf > iron_boot.elf.debug
	qemu-system-arm -S -M $(BOARD) -cpu $(CPU) -nographic -kernel $(PROJECT).elf -gdb tcp::1234

gdb:
	gdb-multiarch -q $(PROJECT).elf -ex "target remote localhost:1234"

clean:
	rm -rf *.out *.elf .gdb_history *.lst *.debug *.o